using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectEuler_Test1
{
    public class Controller
    {

        /*If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.
        The sum of these multiples is 23.

        Find the sum of all the multiples of 3 or 5 below 1000.
        */
        public int NumbersWithMultiplier(int _num)
        {
            int count = 0;

            for(int i = 1; i < _num; i++)
            {
                if (i % 3 == 0 || i % 5 == 0)
                {
                    count += i;
                }
            }

            return count;
        }

        /*Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
        By starting with 1 and 2, the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

        By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
        find the sum of the even-valued terms.
        */

        public int FibonacciWithEven(int limit)
        {
            int first = 1;
            int second = 2;

            int sum = 0;

            for (int i = 3; i <= int.MaxValue; i++)
            {
                int temp = first + second;

                first = second;
                second = temp;

                if (temp % 2 == 0)
                {
                    sum += temp;
                }

                if (temp >= limit)
                    break;
            }

            return sum + 2;
        }
    }
}
